## test
##' Run the Python Preprocessing Pipeline
##'
##' This function runs the three Python preprocessing steps:
##' 1. Generate the single-cell barcode file.
##' 2. Run the fragment overlap counter.
##' 3. Process the overlap counter output.
##'
##' @param filtered_h5 Path to the filtered_feature_bc_matrix.h5 file.
##' @param raw_h5 Path to the raw_feature_bc_matrix.h5 file.
##' @param atac_fragments Path to the atac_fragments.tsv.gz file.
##' @param human_autosomes Path to the human_autosomes.txt file.
##' @param output_directory Directory where all outputs will be saved.
##' @param py_dir Directory where the Python scripts are located.
##' @param rfilter_file Optional path to a repetitive regions filter file.
##'
##' @return The path to the final output file ("colsum.csv") generated by the Python pipeline.
##'
##' @export
run_preprocessing_pipeline <- function(filtered_h5, raw_h5, atac_fragments,
                                       output_directory, rfilter_file = "") {
  # Ensure output directory exists
  if (!dir.exists(output_directory)) {
    dir.create(output_directory, recursive = TRUE)
  }

  # Locate bundled files from the package
  gen_script <- system.file("py", "generate_singlecell.py", package = "SEBULA")
  frag_script <- system.file("py", "FragmentFileOverlapCounter.py", package = "SEBULA")
  process_script <- system.file("py", "process_overlap_counter.py", package = "SEBULA")
  human_autosomes <- system.file("py", "human_autosomes.txt", package = "SEBULA")

  # Step 1: Generate singlecell.csv
  singlecell_cmd <- sprintf(
    "python %s --filtered-h5 %s --raw-h5 %s --output %s",
    shQuote(gen_script), shQuote(filtered_h5), shQuote(raw_h5), shQuote(output_directory)
  )
  message("Running generate_singlecell.py...")
  system(singlecell_cmd)

  singlecell_csv <- file.path(output_directory, "singlecell.csv")

  # Step 2: Run FragmentFileOverlapCounter.py
  frag_cmd <- sprintf(
    "python3 %s %s %s %s %s",
    shQuote(frag_script),
    shQuote(atac_fragments),
    shQuote(singlecell_csv),
    shQuote(human_autosomes),
    shQuote(output_directory)
  )
  message("Running FragmentFileOverlapCounter.py...")
  system(frag_cmd)

  # Step 3: Run process_overlap_counter.py
  overlaps_file <- file.path(output_directory, "Overlaps.txt")
  overlap_summary_file <- file.path(output_directory, "OverlapSummary.txt")

  process_cmd <- sprintf(
    "python3 %s --overlaps %s --overlap-summary %s --output-dir %s",
    shQuote(process_script),
    shQuote(overlaps_file),
    shQuote(overlap_summary_file),
    shQuote(output_directory)
  )

  if (nzchar(rfilter_file)) {
    process_cmd <- paste0(process_cmd, " --rfilter ", shQuote(rfilter_file))
  }

  message("Running process_overlap_counter.py...")
  system(process_cmd)

  # Final check
  colsum_csv <- file.path(output_directory, "colsum.csv")
  if (!file.exists(colsum_csv)) {
    stop("Preprocessing failed: colsum.csv not found.")
  }

  message("✅ Preprocessing pipeline completed successfully.")
  return(colsum_csv)
}




##' Run the Detection Step on Preprocessed Data
##'
##' This function runs the R-based doublet detection on the preprocessed data.
##'
##' @param input Either a file path to the preprocessed CSV (e.g., colsum.csv) or a data frame.
##' @param ... Additional parameters to pass to \code{doublet_cm()}.
##'
##' @return A list with doublet detection results.
##'
##' @export
run_detection <- function(input, ...) {
  if (is.character(input) && file.exists(input)) {
    data <- readr::read_csv(input)
  } else if (is.data.frame(input)) {
    data <- input
  } else {
    stop("Input must be a file path or a data frame containing the preprocessed data.")
  }

  colnames(data) <- c("barcode", "obs")
  message("Running doublet detection in R...")
  # For demonstration, using nulltype = 2 and default parameters.
  result <- doublet_cm(data, ...)
  return(result)
}
